### ISSUE TITLE
Segmentation fault for ReplicaViewer

### ISSUE THREAD

**Issue by priyakasimbeg** [facebookresearch/Replica-Dataset#35]
I am getting  a segfault when I try to run the ReplicaViewer. Here is some the backtrace from gdb: 
```kasimbeg@capri6:/cvgl2/u/kasimbeg/Programs/Replica-Dataset/build/ReplicaSDK$ gdb ReplicaViewer
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ReplicaViewer...(no debugging symbols found)...done.
(gdb) run Data/apartment_0/mesh.ply Data/apartment_0/textures/ Data/apartment_0/glass.sur
Starting program: /cvgl2/u/kasimbeg/Programs/Replica-Dataset/build/ReplicaSDK/ReplicaViewer Data/apartment_0/mesh.ply Data/apartment_0/textures/ Data/apartment_0/glass.sur
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea29a700 (LWP 10951)]
[New Thread 0x7fffe9a99700 (LWP 10952)]
[New Thread 0x7fffe9298700 (LWP 10953)]
[New Thread 0x7fffe8a97700 (LWP 10954)]
[New Thread 0x7fffe8296700 (LWP 10955)]
[New Thread 0x7fffe7a95700 (LWP 10956)]
[New Thread 0x7fffe7294700 (LWP 10957)]
[New Thread 0x7fffe6a93700 (LWP 10958)]
Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.Loaded 15 mirrors

Thread 1 "ReplicaViewer" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) backtrace
#0  0x0000000000000000 in ?? ()
#1  0x0000000000416dbd in MirrorRenderer::MirrorRenderer(std::vector<MirrorSurface, std::allocator<MirrorSurface> > const&, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#2  0x000000000040d964 in main ()
```

**Comment by jstraub** [comment]
Can you clarify which operating system you are working on?

Not sure what this is about:
```
Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.Loaded 15 mirrors
```
@simesgreen ?

**Comment by shubham-goel** [comment]
I running into the same error while working on Ubuntu 18.04!
